name: hzy_normal_network
description: 火之夜网络请求封装库
version: 0.0.1
homepage: https://gitee.com/tengteng_fan/hzy_normal_network.git

environment:
  sdk: ">=2.18.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^4.0.6
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
